-- luacheck configuration for ArchHUD-CC
-- Scoped to the hand-written, shipped flight/HUD logic. DU is global-heavy by
-- design (settings must be global for the databank save/load system, and the
-- minified build collapses everything into one scope), so the global lists below
-- are intentionally large. Regeneration commands are at the bottom of this file.

std = "lua53"
max_line_length = false
codes = true

-- Exclude dev-only scaffolding so the signal stays high:
--   src/du, src/builtin  : DU API stubs / vendored emulator (not shipped logic)
--   du_prologue, slots    : global-wiring files (would clash with read_globals)
--   scripts, tests, board : build tooling, tests, generated board output
exclude_files = {
    "src/du",
    "src/builtin",
    "src/du_prologue.lua",
    "src/slots.lua",
    "scripts",
    "tests",
    "board",
}

ignore = {
    "212", -- unused argument (DI constructors legitimately take many params)
    "213", -- unused loop variable
    "611", "612", "613", "614", -- whitespace
    "631", -- line too long (handled by max_line_length = false)
}

-- DU runtime API, element classes and slot globals: read-only in the linted
-- files (provided by the game and by the excluded slots/prologue wiring).
read_globals = {
    -- namespaces
    "system", "unit", "construct", "player", "library",
    "DUSystem", "DUConstruct", "DUPlayer", "System", "Construct", "Player", "Library",
    -- element classes
    "CoreUnit", "ControlUnit", "RadarPVPUnit", "RadarUnit", "AntiGravityGeneratorUnit",
    "WarpDriveUnit", "GyroUnit", "WeaponUnit", "DataBankUnit", "databank", "TelemeterUnit",
    "TransponderUnit", "VerticalBooster", "Hovercraft", "DoorUnit", "ManualSwitchUnit",
    "ManualButtonUnit", "ForceFieldUnit", "AtmoFuelContainer", "SpaceFuelContainer",
    "RocketFuelContainer", "ShieldGeneratorUnit", "BaseShieldGeneratorUnit", "ScreenUnit",
    "Element", "Engine", "FueledEngine", "AtmosphericEngine", "SpaceEngine", "RocketEngine",
    "Airfoil", "Container", "ItemContainer", "LandingGearUnit", "LightUnit", "CounterUnit",
    "EmitterUnit", "ReceiverUnit", "DetectionZoneUnit", "LaserDetectorUnit",
    "LaserEmitterUnit", "PressureTileUnit", "IndustryUnit", "Firework",
    -- DU-provided helpers
    "json", "vec3", "epsilon", "L_TEXT", "_autoconf",
    -- slot globals (assigned in src/slots.lua, read here)
    "antigrav",
    "atmofueltank",
    "atmofueltank_size",
    "core",
    "dbHud",
    "door",
    "forcefield",
    "gyro",
    "hover",
    "radar",
    "radar_1",
    "radar_2",
    "radar_size",
    "rocketfueltank",
    "rocketfueltank_size",
    "screenHud",
    "screen_1",
    "screen_2",
    "shield",
    "spacefueltank",
    "spacefueltank_size",
    "switch",
    "telemeter",
    "transponder",
    "vBooster",
    "warpdrive",
    "weapon",
    "weapon_size",
}

-- Project globals that ARE assigned within the linted files.
globals = {
    -- class constructors / global functions
    "APClass", "AtlasClass", "ControlClass", "HudClass", "RadarClass", "ShieldClass",
    "TelemetryClass", "programClass", "globalDeclare", "Keplers", "Kinematics", "PlanetRef",
    "GetFuelTankMaxVolume", "GetFuelTankModifier", "GetFuelTankPrefixes",
    -- lifecycle / misc
    "VERSION_NUMBER", "Nav", "PROGRAM", "currentGroundAltitudeStabilization",
    "saveableVariablesBoolean", "saveableVariablesHandling", "saveableVariablesHud",
    "saveableVariablesPhysics", "autoVariables",
    -- user-configurable settings (--export: in src/ArchHUD.lua)
    "AbandonedRadar",
    "AlwaysVSpd",
    "AtmoSpeedAssist",
    "AtmoSpeedLimit",
    "AutoShieldPercent",
    "AutoShieldToggle",
    "AutoTakeoffAltitude",
    "AutopilotInterplanetaryThrottle",
    "AutopilotSpaceDistance",
    "BarFuelDisplay",
    "BrakeToggleDefault",
    "CollisionSystem",
    "ContainerOptimization",
    "DampingMultiplier",
    "DeadZone",
    "DisplayDeadZone",
    "DisplayOdometer",
    "DockingMode",
    "ECUHud",
    "EmergencyWarp",
    "ExternalAGG",
    "ExtraEscapeThrust",
    "ExtraLateralTags",
    "ExtraLongitudeTags",
    "ExtraVerticalTags",
    "FastOrbit",
    "ForceAlignment",
    "FuelTankOptimization",
    "InvertMouse",
    "LandingGearGroundHeight",
    "LowOrbitHeight",
    "MaintainOrbit",
    "MaxGameVelocity",
    "MaxPitch",
    "MouseXSensitivity",
    "MouseYSensitivity",
    "OrbitMapSize",
    "OrbitMapX",
    "OrbitMapY",
    "PitchStallAngle",
    "PreventPvP",
    "PvPB",
    "PvPG",
    "PvPR",
    "ReEntryHeight",
    "ReEntryPitch",
    "RemoteFreeze",
    "ResolutionX",
    "ResolutionY",
    "SafeB",
    "SafeG",
    "SafeR",
    "SetWaypointOnExit",
    "ShiftShowsRemoteButtons",
    "ShouldCheckDamage",
    "SpaceSpeedLimit",
    "TargetHoverHeight",
    "TargetOrbitRadius",
    "TrajectoryAlignmentStrength",
    "VanillaRockets",
    "YawStallAngle",
    "alerts",
    "allowedHorizontalDrift",
    "altMeterX",
    "altMeterY",
    "autoRollFactor",
    "autoRollPreference",
    "autoRollRollThreshold",
    "brakeFlatFactor",
    "brakeLandingRate",
    "brakeSpeedFactor",
    "brightHud",
    "centerX",
    "centerY",
    "circleRad",
    "customAtlas",
    "freeLookToggle",
    "fuelTankHandlingAtmo",
    "fuelTankHandlingRocket",
    "fuelTankHandlingSpace",
    "fuelX",
    "fuelY",
    "hideHudOnToggleWidgets",
    "hudTickRate",
    "minRollVelocity",
    "pitchSpeedFactor",
    "privateFile",
    "radarX",
    "radarY",
    "rollSpeedFactor",
    "shieldX",
    "shieldY",
    "showHud",
    "soundFolder",
    "speedChangeLarge",
    "speedChangeSmall",
    "throtPosX",
    "throtPosY",
    "torqueFactor",
    "useTheseSettings",
    "userControlScheme",
    "vSpdMeterX",
    "vSpdMeterY",
    "voices",
    "warmup",
    "yawSpeedFactor",
    -- shared runtime state (globalDeclare in src/requires/globals.lua)
    "AP",
    "ATLAS",
    "Animated",
    "Animating",
    "AtlasOrdered",
    "CONTROL",
    "HUD",
    "Kep",
    "Kinematic",
    "MaxSpeed",
    "OrbitAchieved",
    "OrbitTargetOrbit",
    "PlayerThrottle",
    "RADAR",
    "ReversalIsOn",
    "SHIELD",
    "SpaceEngineVertDn",
    "SpaceEngines",
    "TELEMETRY",
    "ThrottleLimited",
    "ThrottleValue",
    "UpVertAtmoEngine",
    "WasInCruise",
    "abvGndDet",
    "adjustedAtmoSpeedLimit",
    "adjustedPitch",
    "adjustedRoll",
    "alignHeading",
    "alignTarget",
    "alignmentProgress",
    "antigravOn",
    "apBrk",
    "apButtonsHovered",
    "apScrollIndex",
    "atmoTanks",
    "atmosDensity",
    "autoRoll",
    "autoRollOverrideTime",
    "autopilotTargetPlanet",
    "brakeDistance",
    "brakeInput2",
    "brakeTime",
    "calculatedThrottle",
    "collisionAlertStatus",
    "collisionSavedRoute",
    "collisionTarget",
    "collisionTier",
    "constructForward",
    "constructRight",
    "constructVelocity",
    "coreAltitude",
    "coreMass",
    "coreVelocity",
    "customlocations",
    "distance",
    "finalLand",
    "followMode",
    "galaxyReference",
    "gyroIsOn",
    "hasGear",
    "holdingShift",
    "inAtmo",
    "isBoosting",
    "landingGroundDist",
    "landingSafe",
    "landingStopDist",
    "lastTakeoffPos",
    "leftmouseclick",
    "mouseDistance",
    "msgText",
    "msgTimer",
    "nearPlanet",
    "notPvPZone",
    "oldShowHud",
    "orbitMsg",
    "passengers",
    "pipeDestC",
    "pipeDestT",
    "pipeDistC",
    "pipeDistT",
    "pipePosC",
    "pipePosT",
    "pitchInput",
    "planetAtlas",
    "privatelocations",
    "pvpDist",
    "radarPanelID",
    "reentryModePreference",
    "rocketTanks",
    "rollInput",
    "sEFC",
    "scopeFOV",
    "ships",
    "simulatedX",
    "simulatedY",
    "spaceLand",
    "spaceLaunch",
    "spaceTanks",
    "stalling",
    "throttleMode",
    "time",
    "upAmount",
    "vSpd",
    "velMag",
    "worldPos",
    "worldVertical",
    "yawInput",
}

-- Regenerate the long lists:
--   exports: grep -E '\-\-export:' src/ArchHUD.lua | grep -oE '^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*'
--   state:   sed -n '78,189p' src/requires/globals.lua | grep -oE '^[[:space:]]+[A-Za-z_][A-Za-z0-9_]* ='
